### ISSUE TITLE
KeyError: 'XSRF-TOKEN'

### ISSUE THREAD

**Issue by moli721** [leeeduke/revTongYi#14]
一直存在
```python
Traceback (most recent call last):
  File "D:\visual c++\vscode\code1\revTongYi-0.1.2.1\tests\qianwen.py", line 18, in <module>
    chatbot = qianwen.Chatbot(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\revTongYi\qianwen.py", line 83, in __init__
    "X-Xsrf-Token": self.cookies['XSRF-TOKEN'],
KeyError: 'XSRF-TOKEN'
```
怎么解决
同时我使用Header String，如
```python
import revTongYi.qianwen as qwen

question = "介绍下高考"

chatbot = qwen.Chatbot(
    cookies_str= '我的Header String'
)

print(chatbot.ask(prompt=question))
```
依然报上面的错误

**Comment by moli721** [comment]
破案了，原因是Cookies Header我在授权的时候给的是this site,导致cookies不全
