### ISSUE TITLE
报错 TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by sakmist** [leeeduke/revTongYi#18]
import revTongYi.qianwen as qwen
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2024.1.4\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2024.1.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "Z:\..\..\venv\lib\site-packages\revTongYi\__init__.py", line 9, in <module>
    from . import qianwen
  File "C:\Program Files\JetBrains\PyCharm 2024.1.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "Z:\.....\....\venv\lib\site-packages\revTongYi\qianwen.py", line 22, in <module>
    class Chatbot:
  File "Z:\....\...\venv\lib\site-packages\revTongYi\qianwen.py", line 257, in Chatbot
    def list_session(self) -> list[OrdinaryResponse]:
TypeError: 'type' object is not subscriptable

**Comment by sakmist** [comment]
解决了 需要:Python 3.10 或更高版本  或者删除 -> list[OrdinaryResponse]

**Comment by Chi-Re** [comment]
也可以在源代码的``qianwen.py``的代码的开头添加
```python
from typing import List as list
```
ps:如果按照上面删除的也在``qianwen.py``文件里
以下是函数名``0.1.2.1``版本
```python
def list_session(self) -> list[OrdinaryResponse]:
    ...

def get_session_history(self, sessionId: str) -> list[HistoryResponse]:
    ...
```

**Comment by Chi-Re** [comment]
win7用户的悲伤.jpg

**Comment by old-dream321** [comment]
要不全部改成typing吧，适配一下老版本
